**Codificación de Variables Categóricas**

In [ ]:
#Ordinal
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import LabelEncoder
#Nominal
from sklearn.preprocessing import OneHotEncoder

import pandas as pd
import numpy as np

In [ ]:
#Datos
servicio = ['Muy Insatisfecho', 'Insatisfecho', 'Neutral', 'Satisfecho', 'Muy Satisfecho'] #ORDEN
calidad  = ['Mala', 'Buena', 'Muy Buena', 'Excelente'] #ORDEN

encuesta = {' Servicio' : ['Muy Insatisfecho', 'Insatisfecho', 'Neutral', 'Satisfecho', 'Muy Satisfecho','Muy Insatisfecho'],
            'Alimentos' : ['Mala', 'Buena', 'Muy Buena', 'Excelente', 'Mala', 'Buena'],
            'Cliente Frecuente' : ['No', 'No', 'Sí', 'Sí', 'No', 'Sí']}

cliente = ['No', 'No', 'Sí', 'Sí', 'No', 'Sí'] #Cliente Frecuente

pd.DataFrame(encuesta)

Servicio  Alimentos Cliente Frecuente
0  Muy Insatisfecho       Mala                No
1      Insatisfecho      Buena                No
2           Neutral  Muy Buena                Sí
3        Satisfecho  Excelente                Sí
4    Muy Satisfecho       Mala                No
5  Muy Insatisfecho      Buena                Sí

**1. Codificación Ordinal - 1,2,3,4,...:**

In [ ]:
servicio

['Muy Insatisfecho', 'Insatisfecho', 'Neutral', 'Satisfecho', 'Muy Satisfecho']

In [ ]:
calidad

['Mala', 'Buena', 'Muy Buena', 'Excelente']

In [ ]:
#OrdinalEncoder - MATRICES/TABLAS
datos_ord = pd.DataFrame(encuesta) #Crear el DF
codificador = OrdinalEncoder(categories=[servicio, calidad]) #OBJ. CODIFICAR EN ORDEN 0,1,2,3,... #[], {}, DF, 'blabla..'
codificacion = codificador.fit_transform(datos_ord)

datos_ord = pd.DataFrame(codificacion, columns=['Servicio','Alimentos'])
datos_ord

Servicio  Alimentos
0       0.0        0.0
1       1.0        1.0
2       2.0        2.0
3       3.0        3.0
4       4.0        0.0
5       0.0        1.0

In [ ]:
print(codificador.categories_)

[array(['Muy Insatisfecho', 'Insatisfecho', 'Neutral', 'Satisfecho',
       'Muy Satisfecho'], dtype=object), array(['Mala', 'Buena', 'Muy Buena', 'Excelente'], dtype=object)]


In [ ]:
[array(['Insatisfecho', 'Muy Insatisfecho', 'Muy Satisfecho', 'Neutral',
       'Satisfecho'], dtype=object), array(['Buena', 'Excelente', 'Mala', 'Muy Buena'], dtype=object)]

In [ ]:
cliente

['No', 'No', 'Sí', 'Sí', 'No', 'Sí']

In [ ]:
#LabelEncoder - VECTOR/LISTAS
codificador = LabelEncoder()
codificacion = codificador.fit_transform(cliente)
datos_lab = pd.DataFrame(codificacion, columns=['Cliente'])

datos_lab

Cliente
0        0
1        0
2        1
3        1
4        0
5        1

**2. Codificación Nominal:**

In [ ]:
datos_one = pd.DataFrame(encuesta)
codificador = OneHotEncoder() #OBJ. CODIFICAR SIN ORDEN --> CÓDIGO BINARIO
codifcacion = codificador.fit_transform(datos_one).toarray()  #toarray() para convertir la matriz dispersa en una matriz como tal

#DF
datos_one = pd.DataFrame(codifcacion, columns=np.concatenate(codificador.categories_))
datos_one

Insatisfecho  Muy Insatisfecho  Muy Satisfecho  Neutral  Satisfecho  Buena  \
0           0.0               1.0             0.0      0.0         0.0    0.0   
1           1.0               0.0             0.0      0.0         0.0    1.0   
2           0.0               0.0             0.0      1.0         0.0    0.0   
3           0.0               0.0             0.0      0.0         1.0    0.0   
4           0.0               0.0             1.0      0.0         0.0    0.0   
5           0.0               1.0             0.0      0.0         0.0    1.0   

   Excelente  Mala  Muy Buena  
0        0.0   1.0        0.0  
1        0.0   0.0        0.0  
2        0.0   0.0        1.0  
3        1.0   0.0        0.0  
4        0.0   1.0        0.0  
5        0.0   0.0        0.0

In [ ]:
print(codificador.categories_)

[array(['Insatisfecho', 'Muy Insatisfecho', 'Muy Satisfecho', 'Neutral',
       'Satisfecho'], dtype=object), array(['Buena', 'Excelente', 'Mala', 'Muy Buena'], dtype=object)]


In [ ]:
codifcacion = codificador.fit_transform(datos_one)
print(codifcacion)

  (0, 1)	1.0
  (0, 7)	1.0
  (1, 0)	1.0
  (1, 5)	1.0
  (2, 3)	1.0
  (2, 8)	1.0
  (3, 4)	1.0
  (3, 6)	1.0
  (4, 2)	1.0
  (4, 7)	1.0
  (5, 1)	1.0
  (5, 5)	1.0


**3. Regresión Logística:**

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

c = np.reshape(datos_lab.values, (1,len(datos_lab)))[0]

print('\n OrdinalEncoder: 0,1,2,3,4')
datos_ord = StandardScaler().fit_transform(datos_ord)
m1 = LogisticRegression().fit(datos_ord, c) #MODELO 1
print(f'    Predicciones: {m1.predict(datos_ord)}')
print(f'Clases Correctas: {c}')
print(m1.predict_proba(datos_ord))

print('\n OneHotEncoder: 010101011010')
m2 = LogisticRegression().fit(datos_one, c) #MODELO 2
print(f'    Predicciones: {m2.predict(datos_one)}')
print(f'Clases Correctas: {c}')
print(m2.predict_proba(datos_one))


 OrdinalEncoder: 0,1,2,3,4
    Predicciones: [0 0 1 1 0 1]
Clases Correctas: [0 0 1 1 0 1]
[[0.72281251 0.27718749]
 [0.52005123 0.47994877]
 [0.3104621  0.6895379 ]
 [0.15760361 0.84239639]
 [0.79306827 0.20693173]
 [0.49599553 0.50400447]]

 OneHotEncoder: 010101011010
    Predicciones: [0 0 1 1 0 1]
Clases Correctas: [0 0 1 1 0 1]
[[0.62301432 0.37698568]
 [0.57519021 0.42480979]
 [0.32279763 0.67720237]
 [0.32279763 0.67720237]
 [0.70505958 0.29494042]
 [0.45116842 0.54883158]]


In [ ]:
OneHotEncoder: 010101011010
    Predicciones: [0 0 1 1 0 1]
Clases Correctas: [0 0 1 1 0 1]
[[0.60692253 0.39307747]
 [0.55582032 0.44417968]
 [0.35739719 0.64260281]
 [0.35739719 0.64260281]
 [0.6875462  0.3124538 ]
 [0.4349111  0.5650889 ]]

In [ ]:
pd.DataFrame(encuesta)

Para este ejemplo en especial (de juguete) , la codificación nominal es mejor.

In [ ]:
datos = pd.DataFrame(encuesta)
datos

Servicio  Alimentos Cliente Frecuente
0  Muy Insatisfecho       Mala                No
1      Insatisfecho      Buena                No
2           Neutral  Muy Buena                Sí
3        Satisfecho  Excelente                Sí
4    Muy Satisfecho       Mala                No
5  Muy Insatisfecho      Buena                Sí

In [ ]:
datos.loc[:, ' Servicio'].values

array(['Muy Insatisfecho', 'Insatisfecho', 'Neutral', 'Satisfecho',
       'Muy Satisfecho', 'Muy Insatisfecho'], dtype=object)

In [ ]:
datos.loc[:, ' Servicio'].values.reshape(-1, 1)

array([['Muy Insatisfecho'],
       ['Insatisfecho'],
       ['Neutral'],
       ['Satisfecho'],
       ['Muy Satisfecho'],
       ['Muy Insatisfecho']], dtype=object)

In [ ]:
codificador = OrdinalEncoder(categories=[servicio])
codificacion1 = codificador.fit_transform(datos.loc[:, ' Servicio'].values.reshape(-1,1))
codificacion1

array([[0.],
       [1.],
       [2.],
       [3.],
       [4.],
       [0.]])

In [ ]:
codificador = OneHotEncoder()
codifcacion2 = codificador.fit_transform(datos.loc[:, 'Alimentos'].values.reshape(-1,1)).toarray()
codifcacion2

array([[0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.]])

In [ ]:
tabla = np.concatenate((codificacion1,codifcacion2),1)
pd.DataFrame(tabla, columns=['Servicio', 'Buena', 'Excelente', 'Mala', 'Muy Buena'])

Servicio  Buena  Excelente  Mala  Muy Buena
0       0.0    0.0        0.0   1.0        0.0
1       1.0    1.0        0.0   0.0        0.0
2       2.0    0.0        0.0   0.0        1.0
3       3.0    0.0        1.0   0.0        0.0
4       4.0    0.0        0.0   1.0        0.0
5       0.0    1.0        0.0   0.0        0.0

In [ ]:
tabla

array([[0., 0., 0., 1., 0.],
       [1., 1., 0., 0., 0.],
       [2., 0., 0., 0., 1.],
       [3., 0., 1., 0., 0.],
       [4., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0.]])

In [ ]:
Break a leg!