**Actividad 2:**

In [1]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer

import pandas as pd
import numpy as np

In [2]:
#Datos
df = pd.read_csv('Entrenamiento-Prueba.csv')
x = df.iloc[:, :-1].values
y = df.iloc[:, -1].values
df.head(5)

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [3]:
#Datos Faltantes
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
x[:, 1:3] = imputer.fit_transform(x[:, 1:3])
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [8]:
#Codificar Variables Independientes
from sklearn.preprocessing import RobustScaler
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0]), 
                                     ('num', RobustScaler(), [1,2])])
x = ct.fit_transform(x)
print(x)

[[1.         0.         1.         0.        ]
 [0.         1.         0.         0.        ]
 [0.         1.         0.         1.33333333]
 [0.         1.         0.         0.        ]
 [0.         1.         0.         1.33333333]
 [1.         0.         1.         0.        ]
 [0.         1.         0.         0.        ]
 [1.         0.         1.         0.        ]
 [0.         1.         0.         1.33333333]
 [1.         0.         1.         0.        ]]


In [ ]:
#Codificar Variables Dependientes
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [ ]:
#Datos de Entrenamiento y Prueba
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [ ]:
print(x_train, '\n')
print(x_test, '\n')
print(y_train, '\n')
print(y_test)

[[0.0 0.0 1.0 27.0 48000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 37.0 67000.0]
 [1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 30.0 54000.0]] 

[[0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 48.0 79000.0]] 

[1 0 1 0 1 0 1 0] 

[0 1]


In [ ]:
#Escalado de Características
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [ ]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0]), ('num', RobustScaler(), [1,2])], remainder='passthrough')
ct.fit_transform(x_test)

In [ ]:
print(x_train, '\n')
print(x_test)

[[0.0 0.0 1.0 -1.5578199668313955 -1.3087312010933962]
 [0.0 0.0 1.0 0.15336051486941224 -0.9406505507858784]
 [1.0 0.0 0.0 -0.10493087859486074 0.43965188786731324]
 [1.0 0.0 0.0 0.9120914831707136 0.8997527007517104]
 [1.0 0.0 0.0 -0.39550869624216767 -0.3885295753246018]
 [0.0 1.0 0.0 1.7838249361126344 1.9119744890973844]
 [0.0 1.0 0.0 0.3309358478760997 0.14314247511959086]
 [0.0 1.0 0.0 -1.121953240360435 -0.7566102256321197]] 

[[0.0 0.0 1.0 0.040358030228792745 -0.11246908759396347]
 [1.0 0.0 0.0 1.4932471184653275 1.5438938387898666]]
