<p><img alt="Colaboratory logo" height="140px" src="https://upload.wikimedia.org/wikipedia/commons/archive/f/fb/20161010213812%21Escudo-UdeA.svg" align="left" hspace="10px" vspace="0px"></p>

# **Análisis de Datos y Machine Learning en Python 1**

Juan Camilo Zapata Ceballos   
Facultad de Ciencias Exactas y Naturales   
Universidad de Antioquia   
2023

# **Ejercicios Resueltos**

## <font color='green'>**Ejercicio 1** </font>

Genere los siguientes arreglos 1D:

1. $[0.0 , 0.5, 1.0 , 1.5, 2.0 ]$
2. $[0,  5, 10, 15, 20, 25]$
3. $[1,   4,   9,  16,  25,  36,  49,  64,  81, 100]$

***Ayuda:*** Puede que le sean útiles los métodos $arange$ y $linspace$.

In [ ]:
import numpy as np

In [ ]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [ ]:
np.arange(0,30,5)

array([ 0,  5, 10, 15, 20, 25])

In [ ]:
np.arange(1,11)**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

## <font color='green'>**Ejercicio 2** </font>

Genere los siguientes arreglos 2D:

1. $\begin{pmatrix}
     1 & 2 \\
     3 & 4 \\
  \end{pmatrix}$

2. $\begin{pmatrix}
     1 & 3 \\
     2 & 4 \\
   \end{pmatrix}$

***Ayuda:*** Puede que le sea útil el atributo $T$ para trasponer.


In [ ]:
import numpy as np

In [ ]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [ ]:
a.T

array([[1, 3],
       [2, 4]])

## <font color='green'>**Ejercicio 3** </font>

A partir del siguiente arreglo, efectúe:

&emsp; $a = np.array([0,1,2,3,4,5,6,7,8,9])$

1. Reestructure para que quede con una forma $2\times5$.
2. Reestructure para que quede con una forma $5\times2$.
3. ¿Puede tener una forma diferente a las anteriores? Explique.

***Ayuda:*** Puede que le sean útiles los métodos $reshape$ o $resize$.

In [ ]:
import numpy as np

In [ ]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
a.resize((2,5))
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
a.resize((5,2))
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

La diferencia entre el método $reshape()$ y el $resize()$, recide en que el primero crea un arreglo nuevo con los cambios, es decir, no genera sobrescrituras, sin embargo, el segundo sí genera cambios sobre el arreglo original. Adicionalmente, se puede tener una forma $10\times1$ o una $1\times10$ y en los casos donde la multiplicación entre filas y columnas sea diferente de $10$:

* Se eliminan elementos del arreglo si el tamaño es menor que $10$.
* Hay un error por elementos faltantes, si el tamaño es mayor que $10$.

## <font color='green'>**Ejercicio 4** </font>

Escriba un código que muestre la importancia del método $copy$.

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3])
b = a
c = a.copy()

a[0] = -1
print(f'a = {a}')
print(f'b = {b}')
print(f'c = {c}')

a = [-1  2  3]
b = [-1  2  3]
c = [1 2 3]


## <font color='green'>**Ejercicio 5** </font>

Lea las columnas 1 y 3 del archivo *ER_9_5.txt* como un arreglo 2D. Explique que modificaciones debe hacer para obtener dos arreglos 1D.

***Ayuda 1:*** El archivo se encuentra en la carpeta *Datos/NumPy*.   
***Ayuda 2:*** Intente usar el parámetro $usecols$ del método $loadtxt$.   
***Ayuda 3:*** Intente usar el parámetro $unpack$ del método $loadtxt$.

In [ ]:
import numpy as np

In [ ]:
x = np.loadtxt('ER_9_5.txt', usecols=(0,2), delimiter=' ')
print(f'x = {x}')

x = [[0. 1.]
 [1. 2.]
 [2. 3.]
 [3. 4.]
 [4. 5.]]


In [ ]:
x, y = np.loadtxt('ER_9_5.txt', usecols=(0,2), unpack=True)
print(f'x = {x}')
print(f'y = {y}')

x = [0. 1. 2. 3. 4.]
y = [1. 2. 3. 4. 5.]


## <font color='green'>**Ejercicio 6** </font>

Guarde en un archivo el siguiente conjunto de datos y efectúe:

&emsp;&emsp;&emsp; $x \in [0,1]$,    
&emsp;&emsp;&emsp; $y=x^2$,   
&emsp;&emsp;&emsp; $z=x/2$.   

1. Los datos de $x$ deben contener un decimal.
2. Los datos de $y$ y $z$ deben contener dos decimales.
3. Agregue una cabecera y los espacios necesarios entre columnas.

***Ayuda 1:*** Intente usar el parámetro $fmt$ del método $savetxt$.   
***Ayuda 2:*** Intente usar el parámetro $header$ del método $savetxt$.

In [ ]:
import numpy as np

In [ ]:
#Datos
x = np.linspace(0,1,5)
y = x**2
z = x/2

In [ ]:
#Guardar
datos = np.c_[x,y,z]
formato = ['%.1f','%.2f','%.2f']
cabecera = 'x    y    z'
np.savetxt('ER_9_6.txt', datos, fmt=formato, header=cabecera)

## <font color='green'>**Ejercicio 7** </font>

¿Cuáles son las diferencias entre el operador $+$, el método $add$ y una función que implemente ciclos para sumar los elementos de dos listas?

***Ayuda 1:*** Use los resultados del ejercicio resuelto 6.6.   
***Ayuda 2:*** Use el comando mágico $\%timeit$ para medir el tiempo.

In [ ]:
import numpy as np

In [ ]:
def suma(l1,l2):
  suma = []
  for i,j in zip(l1,l2):
    suma.append(i+j)
  return suma

In [ ]:
numeros_1 = np.linspace(0,1,10000)
numeros_2 = np.linspace(-1,0,10000)

%timeit numeros_1 + numeros_2
%timeit np.add(numeros_1, numeros_2)
%timeit suma(numeros_1, numeros_2)

4.23 µs ± 65.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
4.25 µs ± 78.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
2.22 ms ± 98.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


## <font color='green'>**Ejercicio 8** </font>

Convierta todos los números de la siguiente lista en positivos:

&emsp; $numeros = [-1,2,-3,-4,5,6,-7,-8,-9]$

***Ayuda:*** Puede que le sea útil el método $abs$.



In [ ]:
import numpy as np

In [ ]:
numeros = np.array([-1,2,-3,-4,5,6,-7,-8,-9])
np.abs(numeros)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## <font color='green'>**Ejercicio 9** </font>

Convertir los siguientes ángulos a grados:

&emsp; $angulos\_r = [0,\pi/12,\pi/6,\pi/4,\pi/3,\pi/2,\pi]$

***Ayuda 1:*** Use la constante $\pi$ de NumPy.   
***Ayuda 2:*** La fórmula de conversión es $\theta_{grados}=\frac{180}{\pi}\theta_{rad}$.   
***Ayuda 3:*** Puede que le sea útil el método $degress$.


In [ ]:
import numpy as np

In [ ]:
 π = np.pi
 angulos_r = np.array([0,π/12,π/6,π/4,π/3,π/2,π])
 angulos_g = (180/π)*angulos_r
 angulos_g

array([  0.,  15.,  30.,  45.,  60.,  90., 180.])

In [ ]:
np.degrees(angulos_r)

array([  0.,  15.,  30.,  45.,  60.,  90., 180.])

## <font color='green'>**Ejercicio 10** </font>

Cree una lista con siete números del $0$ a $\pi$ y efectúe:

1. Calcule el seno de esta lista.
2. Calcule el coseno de esta lista.
3. Calcule la suma de los cuadrados de los numerales anteriores.
4. Muestre en pantalla los resultados con un decimal.

***Ayuda 1:*** Puede que le sean útiles las ufuncs $sin$ y $cos$.   
***Ayuda 2:*** Puede que le sea útil la ufunc $around$.

In [ ]:
import numpy as np

In [ ]:
x = np.linspace(0,np.pi,7)
r1 = np.sin(x)
r2 = np.cos(x)
r3 = np.add(np.power(r1,20), np.power(r2,2))

print(f'    x: {np.round(x,1)}')
print(f'  sin: {np.round(r1,1)}')
print(f'  cos: {np.round(r2,1)}')
print(f's2+c2: {np.round(r3,1)}')

    x: [0.  0.5 1.  1.6 2.1 2.6 3.1]
  sin: [0.  0.5 0.9 1.  0.9 0.5 0. ]
  cos: [ 1.   0.9  0.5  0.  -0.5 -0.9 -1. ]
s2+c2: [1.  0.8 0.3 1.  0.3 0.8 1. ]


## <font color='green'>**Ejercicio 11** </font>

Lleve a cabo la suma y el producto de los primeros treinta números naturales de tres en tres.

***Ayuda:*** Puede que le sean útiles los métodos $sum$ y $prod$.

In [ ]:
import numpy as np

In [ ]:
numeros = np.arange(3,31,3)
s = np.sum(numeros)
p = np.prod(numeros)

print(f' Números: {numeros}')
print(f'    Suma: {s}')
print(f'Producto: {p}')

 Números: [ 3  6  9 12 15 18 21 24 27 30]
    Suma: 165
Producto: 214277011200


## <font color='green'>**Ejercicio 12** </font>

Intercambie el valor más pequeño y el más grande dentro de una lista de números.

***Ayuda:*** Puede que le sean útiles los métodos $argmin$ y $argmax$.

In [ ]:
import numpy as np

In [ ]:
numeros = np.array([4,5,3,1,2])
minimo = np.argmin(numeros)
maximo = np.argmax(numeros)

numeros[minimo],numeros[maximo] = numeros[maximo],numeros[minimo]
numeros

array([4, 1, 3, 5, 2])

## <font color='green'>**Ejercicio 13** </font>

Tome el siguiente conjunto de datos y efectúe:

&emsp; $datos = [-2,3,0,1,2,-3,-2,1,0,3]$

1. Calcule la media aritmética y la mediana.
2. Calcule la varianza y la desviación estándar.

***Ayuda 1:*** Puede que le sean útiles las ufuncs $mean$ y $median$.   
***Ayuda 2:*** Puede que le sean útiles las ufuncs $var$ y $std$.   

In [ ]:
import numpy as np

In [ ]:
datos = np.array([-2,3,1,-1,2,-3,-2,1,0,1])
media = np.mean(datos)
mediana = np.median(datos)
varianza = np.var(datos)
desviacion = np.std(datos)

print(f'  Media Aritmética: {media:.2f}')
print(f'           Mediana: {mediana:.2f}')
print(f'          Varianza: {varianza:.2f}')
print(f'Deviación Estándar: {desviacion:.2f}')

  Media Aritmética: 0.00
           Mediana: 0.50
          Varianza: 3.40
Deviación Estándar: 1.84


## <font color='green'>**Ejercicio 14** </font>

A partir del siguiente arreglo, efectúe:

&emsp; $a = np.array([0,1,2,3,4,5,6,7,8,9])$

1. Cambie los números en posiciones pares por negativos.
2. Cambie los números en posiciones impares por su cuadrado.

***Ayuda 1:*** Puede que le sea útil usar la indexación de arreglos.    
***Ayuda 2:*** Puede que le sean útiles los operadores de asignación.




In [ ]:
import numpy as np

In [ ]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
a[0::2] *= -1
a[1::2] **= 2
a

array([ 0,  1, -2,  9, -4, 25, -6, 49, -8, 81])

## <font color='green'>**Ejercicio 15** </font>

A partir del siguiente arreglo, efectúe:

&emsp; $a = np.arange(16).reshape(4,4)$

1. Cree un lista con la tercera fila.
2. Cree un lista con la cuarta columna.




In [ ]:
import numpy as np

In [ ]:
a = np.arange(16).reshape(4,4)
a1 = a[2,:]
a2 = a[:,3]

print(f' a: {a}')
print(f'a1: {a1}')
print(f'a2: {a2}')

 a: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
a1: [ 8  9 10 11]
a2: [ 3  7 11 15]


## <font color='green'>**Ejercicio 16** </font>

De la siguiente lista de números quedese con aquellos que:

&emsp; $numeros = [-1,2,3,-4,-5,-6,7,-8,9]$

1. Sean positivos.
2. Sean pares.
3. Sean negativos e impares.

***Ayuda 1:*** Puede que le sean útiles los operadores de comparación.   
***Ayuda 2:*** Puede que le sean útiles los operadores lógicos.





In [ ]:
import numpy as np

In [ ]:
numeros = np.array([-1,2,3,-4,-5,-6,7,-8,9])
cond_1 = numeros>=0
cond_2 = numeros%2==0
cond_3 = (numeros<0) & (numeros%2!=0)

print(f'          Positivos: {numeros[cond_1]}')
print(f'              Pares: {numeros[cond_2]}')
print(f'Negativos e Impares: {numeros[cond_3]}')

          Positivos: [2 3 7 9]
              Pares: [ 2 -4 -6 -8]
Negativos e Impares: [-1 -5]


## <font color='green'>**Ejercicio 17** </font>

De la siguiente lista de nombres quedese con aquellos que:

&emsp; $nombres = [$'$maria$'$,\ $'$ana$'$,\ $'$camilo$'$,\ $'$sara$'$,\ $'$javier$'$]$

1. Comiencen por la letra $c$.
2. Anteriores a la letra $m$.
3. Entre las letras $c$ y $m$.

***Ayuda:*** Puede que le sea útil el método $char.startswith$.



In [ ]:
import numpy as np

In [ ]:
nombres = np.array(['maria','ana','camilo','sara','javier'])
cond_1 = np.char.startswith(nombres,'c')
cond_2 = nombres<'m'
cond_3 = (nombres>='c') & (nombres<='m')

print(f'  Comienzan por C: {nombres[cond_1]}')
print(f'Anteriores a la M: {nombres[cond_2]}')
print(f'      Entre C y M: {nombres[cond_3]}')

  Comienzan por C: ['camilo']
Anteriores a la M: ['ana' 'camilo' 'javier']
      Entre C y M: ['camilo' 'javier']


## <font color='green'>**Ejercicio 18** </font>

Genere muestras con cinco números aleatorios tal que:

1. Sean enteros entre $-1$ y $1$.
2. Sean flotantes entre $0$ y $1$.

***Ayuda 1:*** Puede que le sea útil el método $random.randint$.   
***Ayuda 2:*** Puede que le sea útil el método $random.uniform$.



In [ ]:
import numpy as np

In [ ]:
muestra_1 = np.random.randint(-1,2,5)
muestra_2 = np.random.uniform(0,1,5)

print(f' Enteros entre -1 y 1: {muestra_1}')
print(f'Flotantes entre 0 y 1: {np.round(muestra_2,2)}')

 Enteros entre -1 y 1: [ 0 -1  0  1  1]
Flotantes entre 0 y 1: [0.19 0.31 0.33 0.34 0.68]


## <font color='green'>**Ejercicio 19** </font>

Tome cuatro muestras aleatorias de la siguiente lista de números:

&emsp; $numeros = [-1,2,3,-4,-5,-6,7,-8,9]$

***Ayuda:*** Puede que le sea útil el método $random.choice$.




In [ ]:
import numpy as np

In [ ]:
numeros = np.array([-1,2,3,-4,-5,-6,7,-8,9])
np.random.choice(numeros,4)

array([ 9, -8,  3, -8])

# **Ejercicios Propuestos**

## <font color='green'>**Ejercicio 1** </font>

Genere los siguientes arreglos:

1. $[-1.0 , -0.5,  0.0 ,  0.5,  1.0 ]$
2. $[ 0.0,  3.0,  6.0,  9.0, 12.0, 15.0, 18.0, 21.0, 24.0, 27.0]$
3. $[ 1,  9, 25, 49, 81]$
4. $[  4,  16,  36,  64, 100]$

***Ayuda:*** Puede que le sean útiles los métodos $arange$ y $linspace$.

In [ ]:
import numpy as np

In [ ]:
np.linspace(-1,1,5)

array([-1. , -0.5,  0. ,  0.5,  1. ])

In [ ]:
np.linspace(0,27,10)

array([ 0.,  3.,  6.,  9., 12., 15., 18., 21., 24., 27.])

In [ ]:
np.arange(1,11,2)**2

array([ 1,  9, 25, 49, 81])

In [ ]:
np.arange(2,11,2)**2

array([  4,  16,  36,  64, 100])

## <font color='green'>**Ejercicio 2** </font>

Explique las semejanzas y diferencias entre $arange$ y $linspace$.

1. arange(inicio, fin, paso)   
2. linspace(inicio, fin, cantidad)
3. Arange no toma el valor final, mientras que, Linspace sí.
4. Linspace siempre es un arreglo de números flotantes.
5. Con ambos se pueden generar los mismo arreglos.

## <font color='green'>**Ejercicio 3** </font>

Cree un arreglo que posea diez elementos y que contenga en todas las entradas el número $5$.

***Ayuda:*** Puede que le sean útiles los métodos $ones$ o $full$.




In [ ]:
import numpy as np

In [ ]:
5*np.ones(10)

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [ ]:
np.full(10,5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

## <font color='green'>**Ejercicio 4** </font>

Cree un arreglo bidimensional (2D) de tamaño $3\times3$ que contenga en todas las entradas el buleano $False$.




In [ ]:
import numpy as np

In [ ]:
np.full((3,3),False)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

## <font color='green'>**Ejercicio 5** </font>

Genere el siguiente arreglo bidimensional::

&emsp;&emsp;&emsp; $\begin{pmatrix}
                     1 & 0 & 0\\
                     0 & 2 & 0\\
                     0 & 0 & 3
  \end{pmatrix}$




In [ ]:
import numpy as np

In [ ]:
np.array([[1,0,0],[0,2,0],[0,0,3]])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

## <font color='green'>**Ejercicio 6** </font>

Genere el siguiente arreglo bidimensional:

&emsp;&emsp;&emsp; $\begin{pmatrix}
                      \ \ \ 1 & \ \ \ 2 & \ \ \ 3\\
                     -1 & -2 & -3\\
                      \ \ \ 3 & \ \ \ 2 & \ \ \ 1
  \end{pmatrix}$

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3])
np.array([a,-a,a[::-1]])

array([[ 1,  2,  3],
       [-1, -2, -3],
       [ 3,  2,  1]])

## <font color='green'>**Ejercicio 7** </font>

Implemente el ejercicio resuelto 9.3 usando el método $reshape$.

In [ ]:
import numpy as np

In [ ]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
a = a.reshape((2,5))
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
a = a.reshape((5,2))
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

## <font color='green'>**Ejercicio 8** </font>

Explique las semejanzas y diferencias entre $reshape$ y $resize$.

1. Reshape no guarda los cambios.
2. Resize si guarda los cambios.
3. Ambos reestructuran un arreglo.

## <font color='green'>**Ejercicio 9** </font>

A partir de un arreglo unidimensional (1D) de tamaño aleatorio:

1. Cree un arreglo 2D cuadrado si el número de elementos de dicho arreglo es un cuadrado perfecto.
2. Muestre un mensaje de error en caso contrario.

***Ayuda 1:*** Puede que le sea útil el atributo $size$.   
***Ayuda 2:*** Puede que le sean útiles los métodos $reshape$ o $resize$.





In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9])
tamaño = a.size
n = int(tamaño**0.5)

if tamaño in [1,4,9,16,25,36]:
  a.resize((n,n))
  print(a)
else:
  print('¡Error!')

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## <font color='green'>**Ejercicio 10** </font>

Guarde en un archivo el siguiente conjunto de datos:

&emsp;&emsp; $x = [0,1,2,3,4,5,6,7,8,9]$,   
&emsp;&emsp; $y = [0,1,4,9,16,25,36,49,64,81]$,

y luego explique que modificaciones debe hacer para que los datos de ambas listas se guarden como números enteros.



In [ ]:
import numpy as np

In [ ]:
#Datos
x = [0,1,2,3,4,5,6,7,8,9]
y = [0,1,4,9,16,25,36,49,64,81]

In [ ]:
#Guardar
np.savetxt('datos.txt', np.c_[x,y], fmt=['%.0f', '%.0f'])

## <font color='green'>**Ejercicio 11** </font>

Guarde en un archivo el siguiente conjunto de datos y efectúe:

&emsp;&emsp; $x = np.linspace(-1,1,100)$,      
&emsp;&emsp; $y = x**-1$,      
&emsp;&emsp; $z = x**3$.

1. Los datos de $x$ deben contener un decimal.
2. Los datos de $y$ y $z$ deben contener dos decimales.
3. Los datos de $y$ y $z$ deben estar en notación científica.
4. Agregue una cabecera y los espacios necesarios entre columnas.





In [ ]:
import numpy as np

In [ ]:
#Datos
x = np.linspace(-1,1,10)
y = x**-1
z = x**3

In [ ]:
#Guardar
formato = ['%4.1f','%9.2e','%9.2e']
cabecera = ' x         y         z'
np.savetxt('datos.txt', np.c_[x,y,z], fmt=formato, header=cabecera)

## <font color='green'>**Ejercicio 12** </font>

Calcule la raíz cuadrada de los siguientes números por dos métodos:

&emsp; $numeros = [0,4,9,16,25,36,49,64,81]$

***Ayuda 1:*** No olvide convertir la lista en un arreglo.   
***Ayuda 2:*** Puede que le sea útil el método $sqrt$.



In [ ]:
import numpy as np

In [ ]:
numeros = np.array([0,4,9,16,25,36,49,64,81])
r1 = numeros**(1/2)
r2 =np.sqrt(numeros)

print(f'Forma 1: {r1}')
print(f'Forma 2: {r2}')

Forma 1: [0. 2. 3. 4. 5. 6. 7. 8. 9.]
Forma 2: [0. 2. 3. 4. 5. 6. 7. 8. 9.]


## <font color='green'>**Ejercicio 13** </font>

Calcule la raíz cúbica de los siguientes números por dos métodos:

&emsp; $numeros = [0,8,27,64,125,216,343,512,729]$

***Ayuda:*** Puede que le sea útil el método $cbrt$.




In [ ]:
import numpy as np

In [ ]:
numeros = np.array([0,8,27,64,125,216,343,512,729])
r1 = numeros**(1/3)
r2 =np.cbrt(numeros)

print(f'Forma 1: {r1}')
print(f'Forma 2: {r2}')

Forma 1: [0. 2. 3. 4. 5. 6. 7. 8. 9.]
Forma 2: [0. 2. 3. 4. 5. 6. 7. 8. 9.]


## <font color='green'>**Ejercicio 14** </font>

Convertir los siguientes ángulos a radianes:

&emsp; $angulos\_g = [0,30,45,60,90,120]$

***Ayuda 1:*** Use la constante $\pi$ de NumPy.   
***Ayuda 2:*** La fórmula de conversión es $\theta_{rad}=\frac{\pi}{180}\theta_{grados}$.   
***Ayuda 3:*** Puede que le sea útil el método $radians$. Consulte.




In [ ]:
import numpy as np

In [ ]:
 π = np.pi
 angulos_g = np.array([0,30,45,60,90,120])
 angulos_r = np.round((π/180)*angulos_g,2)
 angulos_r

array([0.  , 0.52, 0.79, 1.05, 1.57, 2.09])

In [ ]:
np.round(np.radians(angulos_g),2)

array([0.  , 0.52, 0.79, 1.05, 1.57, 2.09])

## <font color='green'>**Ejercicio 15** </font>

Corrobore la identidad trigonométrica $cos(x)=sin(\frac{\pi}{2}+x)$.

***Ayuda:*** Consulte las ufunc trigonométricas.





In [ ]:
import numpy as np

In [ ]:
π = np.pi
x = np.array([0,π/3,π/2,π])
r1 = np.cos(x)
r2 = np.sin(np.pi/2+x)

print(f'Resultado 1: {r1}')
print(f'Resultado 2: {r2}')

Resultado 1: [ 1.000000e+00  5.000000e-01  6.123234e-17 -1.000000e+00]
Resultado 2: [ 1.0000000e+00  5.0000000e-01  1.2246468e-16 -1.0000000e+00]


## <font color='green'>**Ejercicio 16** </font>

Corrobore la identidad trigonométrica $sin(2x)=2sin(x)cos(x)$.




In [ ]:
import numpy as np

In [ ]:
π = np.pi
x = np.array([0,π/3,π/2,π])
r1 = np.sin(2*x)
r2 = 2*np.sin(x)*np.cos(x)

print(f'Resultado 1: {r1}')
print(f'Resultado 2: {r2}')

Resultado 1: [ 0.00000000e+00  8.66025404e-01  1.22464680e-16 -2.44929360e-16]
Resultado 2: [ 0.00000000e+00  8.66025404e-01  1.22464680e-16 -2.44929360e-16]


## <font color='green'>**Ejercicio 17** </font>

Corrobore la identidad trigonométrica $tan(\frac{x}{2})=\frac{sin(x)}{1+cos(x)}$.




In [ ]:
import numpy as np

In [ ]:
π = np.pi
x = np.array([π/6,π/4,π/3,π/2])
r1 = np.tan(x/2)
r2 = np.sin(x)/(1+np.cos(x))

print(f'Resultado 1: {r1}')
print(f'Resultado 2: {r2}')

Resultado 1: [0.26794919 0.41421356 0.57735027 1.        ]
Resultado 2: [0.26794919 0.41421356 0.57735027 1.        ]


## <font color='green'>**Ejercicio 18** </font>

Escriba un programa que clarifique las diferencias entre las ufuncs $around$, $floor$, $ceil$ y $trunc$. Explique.




In [ ]:
import numpy as np

In [ ]:
x = np.array([3.1,3.5,4.5,2.9,-3.1,-3.5,-5.9])
r1 = np.around(x)
r2 = np.floor(x)
r3 = np.ceil(x)
r4 = np.trunc(x)

print(f'around: {r1}')
print(f' floor: {r2}')
print(f'  ceil: {r3}')
print(f' trunc: {r4}')

around: [ 3.  4.  4.  3. -3. -4. -6.]
 floor: [ 3.  3.  4.  2. -4. -4. -6.]
  ceil: [ 4.  4.  5.  3. -3. -3. -5.]
 trunc: [ 3.  3.  4.  2. -3. -3. -5.]


## <font color='green'>**Ejercicio 19** </font>

Efectúe la suma y el producto de los primeros veinte números naturales de uno en uno.




In [ ]:
import numpy as np

In [ ]:
numeros = np.arange(1,21,1)
s = np.sum(numeros)
p = np.prod(numeros)

print(f' Números: {numeros}')
print(f'    Suma: {s}')
print(f'Producto: {p}')

 Números: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
    Suma: 210
Producto: 2432902008176640000


## <font color='green'>**Ejercicio 20** </font>

Efectúe la suma y el producto de los primeros cincuenta números naturales de cinco en cinco.




In [ ]:
import numpy as np

In [ ]:
numeros = np.arange(5,51,5)
s = np.sum(numeros)
p = np.prod(numeros)

print(f' Números: {numeros}')
print(f'    Suma: {s}')
print(f'Producto: {p}')

 Números: [ 5 10 15 20 25 30 35 40 45 50]
    Suma: 275
Producto: 35437500000000


## <font color='green'>**Ejercicio 21** </font>

Use el método $prod$ para calcular el factorial de un número $n$.

***Ayuda:*** Use las ideas del ejercicio propuesto 6.14.




In [ ]:
import numpy as np

In [ ]:
n = 5
x = np.arange(1,n+1,1)
np.prod(x)

120

## <font color='green'>**Ejercicio 22** </font>

Confeccione un código para calcular la moda de un conjunto de datos.

***Ayuda 1:*** Puede que le sea útil el método $unique$. Consulte.   
***Ayuda 2:*** Puede que le sea útil el método $argmax$. Consulte.





In [ ]:
import numpy as np

In [ ]:
numeros = np.array([4,5,2,3,2,1,5,9,2])

def mode(lista):
  unicos, cantidad = np.unique(numeros, return_counts=True)
  pos_max = np.argmax(cantidad)
  moda = unicos[pos_max]
  return moda

print(f'Moda: {mode(numeros)}')

Moda: 2


## <font color='green'>**Ejercicio 23** </font>

¿Cuál es la diferencia entre la media aritmética, la mediana y la moda?, ¿Qué nos dicen sobre un conjunto de datos?

***Ayuda:*** Use los resultados del ejercicio propuesto 9.22.




In [ ]:
import numpy as np

In [ ]:
numeros = np.array([4,5,2,3,2,1,5,9,2])
numeros_o = np.sort(numeros)
media = np.mean(numeros)
mediana = np.median(numeros)
moda = mode(numeros)

print(f'  Lista Original: {numeros}')
print(f'  Lista Ordenada: {numeros_o}')
print(f'Media Aritmética: {media:.2f}')
print(f'         Mediana: {mediana:.2f}')
print(f'            Moda: {moda}')

  Lista Original: [4 5 2 3 2 1 5 9 2]
  Lista Ordenada: [1 2 2 2 3 4 5 5 9]
Media Aritmética: 3.67
         Mediana: 3.00
            Moda: 2


1. Media Aritmética: Promedio de un conjunto de datos.   
2. Mediana: Valor en la mitad en un conjunto de datos.   
3. Moda: El valor que más se repite en un conjunto de datos.  
4. Son medidas de tendencia central, dan un resumen del conjunto de datos.
5. Por lo general sus valores son distintos pero pueden coincidir en algunos casos especiales como en la *Distribución Normal*.

## <font color='green'>**Ejercicio 24** </font>

¿Cuál es la diferencia entre la variancia y la desviación estándar?, ¿Qué nos dicen sobre un conjunto de datos?




In [ ]:
import numpy as np

In [ ]:
numeros = np.array([4,5,2,3,2,1,5,9,2])
varianza = np.var(numeros)
desviacion = np.std(numeros)

print(f'          Varianza: {varianza:.2f}')
print(f'Deviación Estándar: {desviacion:.2f}')
print(f'Deviación Estándar: {np.sqrt(varianza):.2f}')

          Varianza: 5.33
Deviación Estándar: 2.31
Deviación Estándar: 2.31


1. La desviación estándar es la raíz cuadrada de la varianza.
2. Son medidas de dispersión, es decir, indican la separación entre un conjunto de datos.
3. Indican que tan cerca están los datos de la media aritmética.

## <font color='green'>**Ejercicio 25** </font>

Cree un programa que normalice un conjunto de acuerdo a la regla:

&emsp;&emsp;&emsp;&emsp; $\frac{Datos}{Valor \ Máximo}$

1. Calcule las medidas de tendencia central antes y después.
2. Calcule las medidas de dispersión antes y después.
3. ¿Qué observa? Explique.

***Ayuda:*** Use los procedimientos del ejercicio resuelto 9.13.




In [ ]:
import numpy as np

In [ ]:
#Antes
numeros = np.array([4,5,2,3,2,1,5,9,2])
media = np.mean(numeros)
mediana = np.median(numeros)
moda = mode(numeros)
varianza = np.var(numeros)
desviacion = np.std(numeros)

print(f'    Lista Original: {numeros}')
print(f'  Media Aritmética: {media:.2f}')
print(f'           Mediana: {mediana:.2f}')
print(f'              Moda: {moda}')
print(f'          Varianza: {varianza:.2f}')
print(f'Deviación Estándar: {desviacion:.2f}')

    Lista Original: [4 5 2 3 2 1 5 9 2]
  Media Aritmética: 3.67
           Mediana: 3.00
              Moda: 2
          Varianza: 5.33
Deviación Estándar: 2.31


In [ ]:
#Después
numeros_n = numeros/np.max(numeros)
media = np.mean(numeros_n)
mediana = np.median(numeros_n)
moda = mode(numeros_n)
varianza = np.var(numeros_n)
desviacion = np.std(numeros_n)

print(f' Lista Normalizada: {np.round(numeros_n,2)}')
print(f'  Media Aritmética: {media:.2f}')
print(f'           Mediana: {mediana:.2f}')
print(f'              Moda: {moda}')
print(f'          Varianza: {varianza:.2f}')
print(f'Deviación Estándar: {desviacion:.2f}')

 Lista Normalizada: [0.44 0.56 0.22 0.33 0.22 0.11 0.56 1.   0.22]
  Media Aritmética: 0.41
           Mediana: 0.33
              Moda: 2
          Varianza: 0.07
Deviación Estándar: 0.26


1. Los datos cambian de escala de $0$ a $1$.
2. La moda no cambia y todas las demás cantidades estadísticas sí, en una escala basada en el máximo valor.

## <font color='green'>**Ejercicio 26** </font>

Cree un programa que normalice un conjunto de acuerdo a la regla:

&emsp;&emsp;&emsp;&emsp; $\frac{Datos - Media\ Aritm\text{é}tica}{Desviaci\text{ó}n\ Est\text{á}ndar}$

1. Calcule las medidas de tendencia central antes y después.
2. Calcule las medidas de dispersión antes y después.
3. ¿Qué observa? Explique.



In [ ]:
import numpy as np

In [ ]:
#Antes
numeros = np.array([4,5,2,3,2,1,5,9,2])
media = np.mean(numeros)
mediana = np.median(numeros)
moda = mode(numeros)
varianza = np.var(numeros)
desviacion = np.std(numeros)

print(f'    Lista Original: {numeros}')
print(f'  Media Aritmética: {media:.2f}')
print(f'           Mediana: {mediana:.2f}')
print(f'              Moda: {moda}')
print(f'          Varianza: {varianza:.2f}')
print(f'Deviación Estándar: {desviacion:.2f}')

    Lista Original: [4 5 2 3 2 1 5 9 2]
  Media Aritmética: 3.67
           Mediana: 3.00
              Moda: 2
          Varianza: 5.33
Deviación Estándar: 2.31


In [ ]:
#Después
numeros_n = (numeros-media)/desviacion
media = np.mean(numeros_n)
mediana = np.median(numeros_n)
moda = mode(numeros_n)
varianza = np.var(numeros_n)
desviacion = np.std(numeros_n)

print(f' Lista Normalizada: {np.round(numeros_n,2)}')
print(f'  Media Aritmética: {media:.2f}')
print(f'           Mediana: {mediana:.2f}')
print(f'              Moda: {moda}')
print(f'          Varianza: {varianza:.2f}')
print(f'Deviación Estándar: {desviacion:.2f}')

 Lista Normalizada: [ 0.14  0.58 -0.72 -0.29 -0.72 -1.15  0.58  2.31 -0.72]
  Media Aritmética: 0.00
           Mediana: -0.29
              Moda: 2
          Varianza: 1.00
Deviación Estándar: 1.00


1. Los datos se centran en cero y cambian de escala. Algunos pasan a ser negativos.
2. La media aritmética se convierte en $0$, la mediana se corre y la moda no cambia.
3. La varianza y la desviación estándar se convierten en $1$.

## <font color='green'>**Ejercicio 27** </font>

Calcule las medidas de tendencia central y de dispersión para la estutura y la edad del grupo de Python para Jóvenes.

In [ ]:
#POR DESARROLAR

## <font color='green'>**Ejercicio 28** </font>

A partir del siguiente arreglo, efectúe:

&emsp; $a = np.arange(16).reshape(4,4)$

1. Obtenga la matriz $2\times2$ superior izquierda.
2. Obtenga la matriz $2\times2$ inferior derecha.

***Ayuda:*** Use indexación y segmentación de arreglos.




In [ ]:
import numpy as np

In [ ]:
a = np.arange(16).reshape(4,4)
a1 = a[:2,:2]
a2 = a[2:,2:]

print(f' a: {a}')
print(f'a1: {a1}')
print(f'a2: {a2}')

 a: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
a1: [[0 1]
 [4 5]]
a2: [[10 11]
 [14 15]]


## <font color='green'>**Ejercicio 29** </font>

Con el arreglo del ejercicio propuesto 9.28 cambie los números en la matriz $2\times2$ interna por su equivalente negativo.




In [ ]:
import numpy as np

In [ ]:
a = np.arange(16).reshape(4,4)
a[1:3,1:3] *=-1
a

array([[  0,   1,   2,   3],
       [  4,  -5,  -6,   7],
       [  8,  -9, -10,  11],
       [ 12,  13,  14,  15]])

## <font color='green'>**Ejercicio 30** </font>

Con el arreglo del ejercicio propuesto 9.28 obtenga una matriz con los números pares.



In [ ]:
import numpy as np

In [ ]:
a = np.arange(16).reshape(4,4)
a[::1,::2]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14]])

## <font color='green'>**Ejercicio 31** </font>

Con el arreglo del ejercicio propuesto 9.28 obtenga una matriz con los números impares.




In [ ]:
import numpy as np

In [ ]:
a = np.arange(16).reshape(4,4)
a[::1,1::2]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15]])

## <font color='green'>**Ejercicio 32** </font>

De la siguiente lista de números quedese con aquellos que sean positivos, impares y divisibles por tres:

&emsp; $numeros = [-1,2,3,-4,-5,-6,7,-8,9]$

***Ayuda 1:*** Puede que le sean útiles los operadores de comparación.   
***Ayuda 2:*** Puede que le sean útiles los operadores lógicos.




In [ ]:
import numpy as np

In [ ]:
numeros = np.array([-1,2,3,-4,-5,-6,7,-8,9])
cond_1 = numeros>=0
cond_2 = numeros%2!=0
cond_3 = numeros%3==0
cond_4 = (cond_1) & (cond_2) & (cond_3)

numeros[cond_4]

array([3, 9])

## <font color='green'>**Ejercicio 33** </font>

A partir del ejercicio propuesto 9.32 quedese con aquellos números que sean negativos, pares y divisibles por cuatro.



In [ ]:
import numpy as np

In [ ]:
numeros = np.array([-1,2,3,-4,-5,-6,7,-8,9])
cond_1 = numeros<0
cond_2 = numeros%2==0
cond_3 = numeros%4==0
cond_4 = (cond_1) & (cond_2) & (cond_3)

numeros[cond_4]

array([-4, -8])

## <font color='green'>**Ejercicio 34** </font>

A partir del ejercicio propuesto 9.32 quedese con aquellos números que sean negativos y divisibles por dos o tres.



In [ ]:
import numpy as np

In [ ]:
numeros = np.array([-1,2,3,-4,-5,-6,7,-8,9])
cond_1 = numeros<0
cond_2 = (numeros%2==0) | (numeros%3==0)
cond_3 = (cond_1) & (cond_2)

numeros[cond_3]

array([-4, -6, -8])

## <font color='green'>**Ejercicio 35** </font>

¿Cuál es la diferencia entre enmascarar y filtrar?




In [ ]:
import numpy as np

In [ ]:
numeros = np.array([1,2,3,4,5,6,7,8,9])
print(f'Enmascarar: {numeros<5}')
print(f'   Filtrar: {numeros[numeros<5]}')

Enmascarar: [ True  True  True  True False False False False False]
   Filtrar: [1 2 3 4]


1. Enmascarar es convertir un arreglo en valores buleanos dada una condición.
2. Filtar es pasar dicha máscara como índices a un arreglo.

## <font color='green'>**Ejercicio 36** </font>

¿Cuál es la diferencia entre las listas de Python Nativo y los arreglos de NumPy a nivel de enmascarar y filtrar?




In [ ]:
import numpy as np

In [ ]:
#Python Nativo
numeros = [1,2,3,4,5,6,7,8,9]
numeros[numeros<5]

TypeError: ignored

In [ ]:
#Python Nativo + Ciclo
numeros = [1,2,3,4,5,6,7,8,9]
numeros_ = []

for numero in numeros:
  if numero<5:
    numeros_.append(numero)

numeros_

[1, 2, 3, 4]

In [ ]:
#Python Nativo + Filter
numeros = [1,2,3,4,5,6,7,8,9]
list(filter(lambda n:n<5, numeros))

[1, 2, 3, 4]

In [ ]:
#Numpy
numeros = np.array([1,2,3,4,5,6,7,8,9])
numeros[numeros<5]

array([1, 2, 3, 4])

Una lista de Python no permite realizar enmascaramiento, los arreglos de Numpy sí. Por ende, para llevar a cabo un filtro sobre una lista debe implementarse un ciclo o el método nativo $filter$.

## <font color='green'>**Ejercicio 37** </font>

De la siguiente lista de nombres quedese con aquellos que comiencen por la letra $m$ y terminen por $a$:

&emsp; $nombres = [$'$maria$'$,\ $'$ana$'$,\ $'$camilo$'$,\ $'$sara$'$,\ $'$manuela$'$]$

***Ayuda 1:*** Puede que le sea útil el método $char.startswith$. Consulte.  
***Ayuda 2:*** Puede que le sea útil el método $char.endswith$. Consulte.




In [ ]:
import numpy as np

In [ ]:
nombres = np.array(['maria','ana','camilo','sara','manuela'])
cond_1 = np.char.startswith(nombres,'m')
cond_2 = np.char.endswith(nombres,'a')
cond_3 = cond_1 & cond_2

nombres[cond_3]

array(['maria', 'manuela'], dtype='<U7')

## <font color='green'>**Ejercicio 38** </font>

De la siguiente lista de nombres quedese con aquellos que contengan exactamente dos $a$:

&emsp; $nombres = [$'$maria$'$,\ $'$ana$'$,\ $'$camilo$'$,\ $'$alejandra$'$]$

***Ayuda 1:*** Cree una función para contar caracteres.   
***Ayuda 2:*** Puede que le sea útil el método $count$. Consulte.




In [ ]:
import numpy as np

In [ ]:
def contar(lista,caracter,repeticion):
  enmascarar = []

  for cadena in lista:
    if cadena.count(caracter)==repeticion:
       enmascarar.append(True)
    else:
      enmascarar.append(False)

  return enmascarar

In [ ]:
nombres = np.array(['maria','ana','camilo','alejandra'])
cond = contar(nombres,'a',2)
nombres[cond]

array(['maria', 'ana'], dtype='<U9')

## <font color='green'>**Ejercicio 39** </font>

Generalice el ejercicio propuesto 9.38 para incluir nombres que:

1. Contengan exactamente dos $a$.
2. Contengan al menos dos $a$.
3. Contengan a lo sumo dos $a$.




In [ ]:
import numpy as np

In [ ]:
def contar(lista, caracter, repeticion, operacion):
  enmascarar = []

  for cadena in lista:
    condicion = eval(str(cadena.count(caracter)) + operacion + str(repeticion))
    if condicion:
       enmascarar.append(True)
    else:
      enmascarar.append(False)

  return enmascarar

In [ ]:
nombres = np.array(['maria','ana','camilo','alejandra'])
cond_1 = contar(nombres,'a',2,'==')
cond_2 = contar(nombres,'a',2,'>=')
cond_3 = contar(nombres,'a',2,'<=')

print(f'          Dos "a": {nombres[cond_1]}')
print(f' Al menos dos "a": {nombres[cond_2]}')
print(f'A lo sumo dos "a": {nombres[cond_3]}')

          Dos "a": ['maria' 'ana']
 Al menos dos "a": ['maria' 'ana' 'alejandra']
A lo sumo dos "a": ['maria' 'ana' 'camilo']


## <font color='green'>**Ejercicio 40** </font>

¿Qué es un número pseudoaleatorio? ¿Qué es la semilla (seed)?




1. Un número pseudoaleatorio es un número generado en un proceso determinista (usando una ecuación).
2. Las secuencias de números pseudoaleatorios no muestran ningún patrón aparante, sin embargo, en las mismas condiciones iniciales siempre producen identicos resultados.
3. La semilla es la condición inicial para generar un secuencia de números aleatorios.
4. En NumPy, la semilla siempre es la hora y la fecha exacta del momento en que se ejecuta el código.

## <font color='green'>**Ejercicio 41** </font>

¿Cuál es la diferencia entre las distribuciones uniforme y normal?

***Ayuda:*** Complemente las ideas con el ejercicio propuesto 10.21.



In [ ]:
import numpy as np

In [ ]:
uniforme = np.random.uniform(-1,1,1000000)
normal = np.random.normal(0,1,1000000)

print('Uniforme')
print(f'              Media: {np.mean(uniforme):5.2f}')
print(f'            Mediana: {np.median(uniforme):5.2f}')
print(f'           Varianza: {np.var(uniforme):5.2f}')
print(f'Desviación Estándar: {np.std(uniforme):5.2f}')

print('\nNormal')
print(f'              Media: {np.mean(normal):5.2f}')
print(f'            Mediana: {np.median(normal):5.2f}')
print(f'           Varianza: {np.var(normal):5.2f}')
print(f'Desviación Estándar: {np.std(normal):5.2f}')

Uniforme
              Media:  0.00
            Mediana: -0.00
           Varianza:  0.33
Desviación Estándar:  0.58

Normal
              Media:  0.00
            Mediana:  0.00
           Varianza:  1.00
Desviación Estándar:  1.00


## <font color='green'>**Ejercicio 42** </font>

Lleve a cabo un programa que ayude a un usuario a generar una contraseña aleatoria con una cantidad definida de caracteres, los cuales pueden ser números o letras en mínuscula.

***Ayuda 1:*** Puede que le sea útil la ufunc $concatenate$.   
***Ayuda 2:*** Puede que le sea útil el método $random.choice$.   





In [ ]:
import numpy as np

In [ ]:
numeros = np.array([0,1,2,3,4,5,6,7,8,9])
letras = np.array(['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z'])
caracteres = np.concatenate((numeros,letras))
contraseña = ''
n = 10
i = 0

while i<n:
  contraseña += np.random.choice(caracteres)
  i += 1

contraseña

'7s6ked0asi'

## <font color='green'>**Ejercicio 43** </font>

Confeccione un programa para mostrar todas las posibles permutaciones entre los números $1$, $2$ y $3$.

***Ayuda 1:*** Hay seis permutaciones posibles.   
***Ayuda 2:*** Puede que le sea útil el método $random.permutation$.




In [ ]:
import numpy as np

In [ ]:
numeros = np.array([1,2,3])
permutaciones = []

while len(permutaciones)<6:
  permutacion = list(np.random.permutation(numeros))
  if permutacion not in permutaciones:
    permutaciones.append(permutacion)

sorted(permutaciones)

[[1, 2, 3], [1, 3, 2], [2, 1, 3], [2, 3, 1], [3, 1, 2], [3, 2, 1]]

## <font color='green'>**Ejercicio 44** </font>

Confeccione un programa para mostrar todas las posibles permutaciones entre los números $1$, $2$, $3$ y $4$.

***Ayuda:*** ¿Cuántas posibles permutaciones hay?.   




In [ ]:
import numpy as np

In [ ]:
numeros = np.array([1,2,3,4])
permutaciones = []

while len(permutaciones)<24:
  permutacion = list(np.random.permutation(numeros))
  if permutacion not in permutaciones:
    permutaciones.append(permutacion)

sorted(permutaciones)

[[1, 2, 3, 4],
 [1, 2, 4, 3],
 [1, 3, 2, 4],
 [1, 3, 4, 2],
 [1, 4, 2, 3],
 [1, 4, 3, 2],
 [2, 1, 3, 4],
 [2, 1, 4, 3],
 [2, 3, 1, 4],
 [2, 3, 4, 1],
 [2, 4, 1, 3],
 [2, 4, 3, 1],
 [3, 1, 2, 4],
 [3, 1, 4, 2],
 [3, 2, 1, 4],
 [3, 2, 4, 1],
 [3, 4, 1, 2],
 [3, 4, 2, 1],
 [4, 1, 2, 3],
 [4, 1, 3, 2],
 [4, 2, 1, 3],
 [4, 2, 3, 1],
 [4, 3, 1, 2],
 [4, 3, 2, 1]]